/*
 * This file was generated by gots, do not edit it manually
 * You can find the docs and source code at https://github.com/aosasona/gots
 */
	
export type Admin = {
    enabled?: boolean;
    port?: number;
    api_key?: string;
    confirm_disable?: boolean;
};

export type Service = {
    host?: string;
    port?: number;
    enable_tls?: boolean | null;
    domains: Domain[];
};

export type DomainStatusCert = {
    value: 'issued' | 'pending' | 'failed';
    last_updated: number;
};

export type DomainStatusDNS = {
    value: 'verified' | 'pending' | 'aborted';
    retry: Retry;
    last_updated: number;
};

export type DomainStatus = {
    cert: DomainStatusCert;
    dns: DomainStatusDNS;
};

export type Retry = {
    max_tries: number;
    interval: number;
    current_tries: number;
};

export type Domain = {
    name: string;
    status: DomainStatus;
};

export type Proxy = {
    host?: string;
    http_port?: number;
    https_port?: number;
    data_dir?: string;
    storage: 'json' | 'sqlite';
    cnames: string[];
};

export type Config = {
    admin: Admin;
    services: Record<string, Service>;
    proxy: Proxy;
};