/*
 * This file was generated by gots, do not edit it manually
 * You can find the docs and source code at https://github.com/aosasona/gots
 */
	
export type Admin = {
    enabled: boolean;
    port: number;
    api_key: string;
};

export type Service = {
    host: string;
    port: number;
    enable_tls: boolean;
};

export type Proxy = {
    host: string;
    port: number;
    tls_port: number;
    data_dir: string;
    storage: 'json' | 'sqlite';
};

export type Config = {
    admin: Admin;
    services: Record<string, Service>;
    proxy: Proxy;
};